name: Executed Automated E2E Tests
run-name: Automated E2E Tests in ${{ github.event.inputs.environment }} environment by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to checkout?
        required: true
        default: master
      environment:
        description: Which environment?
        required: true
        type: environment
        default: prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-proress: true

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
  e2e-tests:
    needs: [setup-runner]
    environment: ${{ github.event.inputs.environment }}
    runs-on: ${{ needs.setup-runner.outputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install Dependencies
        run: npm install
      - name: Make .env file
        run: |
          TEMPLATE_FILE=.env.example
          TARGET_FILE=.env
          cp $TEMPLATE_FILE $TARGET_FILE
      - name: Run E2E Tests in ${{ github.event.inputs.environment }} environment
        run: npm test
      - name: Upload E2E Tests Result
        if: ${{ always() }}
        uses: actions/upload-aftifact@v4
        with:
          name: test-execution-results
          path: ./test-results/
