name: Executed Automated E2E Tests
run-name: Automated E2E Tests in ${{ github.event.inputs.environment }} environment by ${{ github.actor }}
env:
  RUNNER_MOCK: ubuntu-latest
  RUNNER_PROD: ubuntu-latest
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment?
        required: true
        default: prod
        type: choice
        options:
          - prod
          - mock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - name: Check environment and set the runner
        id: set-runner
        run: |
          if [ ${{ github.event.inputs.environment }} == 'mock' ]; then
            echo "runnner=$RUNNER_MOCK" >> $GITHUB_OUTPUT
          else
            echo "runnner=$RUNNER_PROD" >> $GITHUB_OUTPUT
          fi
  e2e-tests:
    needs: [setup-runner]
    environment: ${{ github.event.inputs.environment }}
    runs-on: ${{ needs.setup-runner.outputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install Dependencies
        run: npm install
      - name: Make .env file
        run: |
          TEMPLATE_FILE=.env.example
          TARGET_FILE=.env
          cp $TEMPLATE_FILE $TARGET_FILE
      - name: Run E2E Tests in ${{ github.event.inputs.environment }} environment
        run: npm test
      - name: Upload E2E Tests Result
        if: ${{ always() }}
        uses: actions/upload-aftifact@v4
        with:
          name: test-execution-results
          path: ./test-results/
